pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [sideeffffect]
      label:
        add: ["type: dependencies"]
  - name: label scala-steward's breaking PRs
    conditions:
      - author=scala-steward
      - "body~=(labels: library-update, semver-major)|(labels: sbt-plugin-update, semver-major)"
    actions:
      label:
        add: ["type: breaking"]
  - name: merge Scala Steward's PRs
    conditions:
      - base=master
      - author=scala-steward
      - status-success=ci
      - "body~=(labels: library-update, semver-minor)|(labels: library-update, semver-patch)|(labels: sbt-plugin-update, semver-minor)|(labels: sbt-plugin-update, semver-patch)|(labels: scalafix-rule-update)|(labels: test-library-update)"
    actions:
      merge:
        method: squash
  - name: automatic merge for master when CI passes
    conditions:
      - base=master
      - label=mergify-merge
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - status-success=ci
    actions:
      merge:
        method: squash
  - name: automatic update for PR marked mergify-update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label="mergify-update"
    actions:
      update: {}
