[package]
name = "adder"
version = "0.1.0"
authors = ["Ondra Pelech <ondra.pelech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19"

[lib]
crate_type = ["cdylib"]
